image: debian:testing

test:
  script:
    - apt-get update
    - apt-get install -y python3-crypto python3-dateutil python3-idna python3-numpy python3-pil.imagetk python3-pycryptodome python3-requests python3-socks python3-setuptools
    - python3 epicyon.py --tests
    - python3 epicyon.py --testsnetwork
